apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkbWwwMDQuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHVjJiM0J6TURBMFFHZHRZV2xzTG1OdmJUcFFiR1ZoYzJWemFYSXgiCgkJfSwKCQkidmFsYXh5MDUuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHVjJiM0J6TURBMFFHZHRZV2xzTG1OdmJUcFFiR1ZoYzJWemFYSXgiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson

